/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ramki;

import java.util.Set;
import javax.ws.rs.core.Application;

/**
 *
 * @author ramki
 */
@javax.ws.rs.ApplicationPath("rest")
public class ApplicationConfig extends Application {

    @Override
    public Set<Class<?>> getClasses() {
        Set<Class<?>> resources = new java.util.HashSet<Class<?>>();
        addRestResourceClasses(resources);
        return resources;
    }

    /**
     * Do not modify addRestResourceClasses() method.
     * It is automatically re-generated by NetBeans REST support to populate
     * given list with all resources defined in the project.
     */
    private void addRestResourceClasses(Set<Class<?>> resources) {
        resources.add(com.ramki.CloudResource.class);
    }
    
}
